# Generated by Django 5.1.4 on 2025-01-25 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0002_rename_bus_id_schedule_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BusCompany.bus'),
        ),
    ]
