# Generated by Django 5.1.4 on 2025-01-25 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0003_alter_schedule_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='rout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BusCompany.rout'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BusCompany.schedule'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BusCompany.user'),
        ),
    ]
