# Generated by Django 5.1.4 on 2025-02-07 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0005_alter_bus_bus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 7, 14, 16, 22, 292342)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
