# Generated by Django 5.1.7 on 2025-03-19 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0006_schedule_date_alter_bus_bus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='number_of_seats_left',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 18, 34, 5, 449985)),
        ),
    ]
