# Generated by Django 5.1.7 on 2025-03-20 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0007_bus_number_of_seats_left_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 20, 15, 37, 4, 423946)),
        ),
    ]
