# Generated by Django 5.1.7 on 2025-03-26 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0013_alter_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 26, 10, 47, 24, 104711)),
        ),
    ]
