# Generated by Django 5.1.7 on 2025-04-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0015_remove_bus_company_id_remove_schedule_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
