# Generated by Django 5.1.7 on 2025-04-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0016_alter_user_username'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AbsUser',
        ),
    ]
