# Generated by Django 5.1.7 on 2025-04-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0017_rename_user_absuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbsUser',
            new_name='User',
        ),
    ]
