# Generated by Django 5.1.7 on 2025-04-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusCompany', '0019_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
