# Generated by Django 5.1.7 on 2025-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_departure_number', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('number_of_seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('remaimning_seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
