# Generated by Django 5.1.7 on 2025-04-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDBusAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_departure_number',
            new_name='bus_identification_number',
        ),
    ]
