# Generated by Django 5.1.4 on 2025-01-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rout',
            fields=[
                ('rout_id', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Capacity', models.IntegerField()),
                ('VIP', models.BooleanField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusCompany.company')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('arrivale_time', models.TimeField()),
                ('bus_id', models.ForeignKey(default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, to='BusCompany.bus')),
                ('rout_id', models.ForeignKey(default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, to='BusCompany.rout')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(default=2)),
                ('seat_number', models.IntegerField()),
                ('number_of_travelers', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('booking_date', models.ForeignKey(default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, to='BusCompany.schedule')),
                ('user_id', models.ForeignKey(default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, to='BusCompany.user')),
            ],
        ),
    ]
