# Generated by Django 5.1.7 on 2025-04-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
