# Generated by Django 5.1.7 on 2025-04-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='iamalove', max_length=300),
            preserve_default=False,
        ),
    ]
