# Generated by Django 5.1.7 on 2025-04-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
